Validate blockhash that the relayer responds with
flashbots/mev-boost pull request #299
Opened 2022-09-09 01:37 UTC by avalonche

## 📝 Summary

Validates the block hash the relay responds with the hash calculated from the relay block.

## ⛱ Motivation and Context

Resolves https://github.com/flashbots/mev-boost/issues/280
## 📚 References

---

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`

2022-09-09 07:58 UTC, metachris commented on go.mod
> +	github.com/flashbots/go-boost-utils v1.0.1-0.20220908121238-1df8f336bae3
v1.0.0 should have everything?

2022-10-17 21:02 UTC, jtraglia requested changes
Looks like a good check to have 👍 one small suggestion though.

2022-10-17 21:02 UTC, jtraglia commented on server/service_test.go
> +	// })
Please delete the commented out test.

```suggestion
```

2022-10-19 10:48 UTC, metachris approved these changes

2022-10-19 10:48 UTC, metachris commented on server/service_test.go
> +	// })
nice, committed

2022-10-19 15:10 UTC, jtraglia approved these changes
LGTM 👍

2022-10-20 11:15 UTC, merged